const products = [
    {
        "name": "Webroot SecureAnywhere Internet Security (3-Device) (1-Year Subscription) - Mac/Windows",
        "shortDescription": "Safeguard your PC, Mac, Android and iOS devices with comprehensive Internet protection",
        "quantity": 4,
        "salePrice": 49.99,
        "manufacturer": "Webroot",
        "type": "Software",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1688/1688832_105x210_sc.jpg",
        "shipping": "Free shipping",
        "id": 0
    },
    {
        "name": "Geek Squad® - Tech Support Membership (1 Year)",
        "shortDescription": "Who has time for frustrating computer issues? With unlimited coverage for all your computing issues, Geek Squad Tech Support is the expert resource you need to keep your PC, Mac or tablet (up to three devices) up and running, no matter where you bought them. Get convenient help any way you'd like: in store, online or on the phone.",
        "quantity": 7,
        "salePrice": 199.99,
        "manufacturer": "Geek Squad®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1853/1853259_sc.jpg",
        "shipping": "Free shipping",
        "id": 1
    },
    {
        "name": "Apple® - 3.3' Lightning-to-USB 2.0 Cable",
        "shortDescription": "Compatible with most Apple® iPad®, iPhone® and iPod® models with a Lightning connector; charges and syncs your device; reversible design",
        "quantity": 12,
        "salePrice": 19.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6652/6652043_sc.jpg",
        "shipping": null,
        "id": 2
    },
    {
        "name": "Google - Chromecast HDMI Streaming Media Player",
        "shortDescription": "Casts online video and music to your HDTV from popular apps like Netflix, YouTube, HBO GO, Hulu Plus, Pandora, Crackle, ESPN, MLB.TV, Google Play Movies & TV, Google Play Music, Chrome* and more; plug in and play; works across platforms; no remote required",
        "quantity": 17,
        "salePrice": 35,
        "manufacturer": "Google",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9071/9071056_sc.jpg",
        "shipping": "Free shipping",
        "id": 3
    },
    {
        "name": "Kaspersky Internet Security (3-Device) (1-Year Subscription) - Mac/Windows",
        "shortDescription": "Provide comprehensive protection to up to three devices in your home",
        "quantity": 24,
        "salePrice": 49.99,
        "manufacturer": "Kaspersky Lab",
        "type": "Software",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1689/1689012_sc.jpg",
        "shipping": "Free shipping",
        "id": 4
    },
    {
        "name": "Logitech - Marathon Mouse M705 Wireless Laser Mouse - Black",
        "shortDescription": "Laser technology; Unifying receiver; wireless USB interface",
        "quantity": 25,
        "salePrice": 39.99,
        "manufacturer": "Logitech",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1325/1325119_sc.jpg",
        "shipping": "Free shipping",
        "id": 5
    },
    {
        "name": "Toshiba - Satellite 15.6\" Laptop - Intel Celeron - 4GB Memory - 500GB Hard Drive - Jet Black",
        "shortDescription": "Windows 8.1 64-bitTechnical details: Intel® Celeron® processor; 15.6\" display; 4GB memory; 500GB hard driveSpecial features: HDMI outputNote: DVD/CD drive not included",
        "quantity": 28,
        "salePrice": 228.99,
        "manufacturer": "Toshiba",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6841/6841014_sc.jpg",
        "shipping": "Free shipping",
        "id": 6
    },
    {
        "name": "SanDisk - Cruzer 16GB USB 2.0 Flash Drive - Black",
        "shortDescription": "For PC, Mac and Linux; retractable USB connector; drag-and-drop file backup; includes SanDisk SecureAccess software; access to 2GB of YuuWaa Cloud storage",
        "quantity": 29,
        "salePrice": 7.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9226/9226875_sc.jpg",
        "shipping": "Free shipping",
        "id": 7
    },
    {
        "name": "SanDisk - Ultra Plus 16GB SDHC Class 10 UHS-1 Memory Card",
        "shortDescription": "Compatible with most devices with a SDHC card slot; 16GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
        "quantity": 34,
        "salePrice": 14.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142535_sc.jpg",
        "shipping": "Free shipping",
        "id": 8
    },
    {
        "name": "Office Home & Student 2013 - Windows",
        "shortDescription": "Create, communicate and learn using streamlined touch, pen or keyboard commands",
        "quantity": 39,
        "salePrice": 139.99,
        "manufacturer": "Microsoft",
        "type": "Software",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7016/7016127_105x105_sc.jpg",
        "shipping": "Free shipping",
        "id": 9
    },
    {
        "name": "Apple® - TV",
        "shortDescription": "3rd generation; compatible with most HDTVs with an HDMI interface; allows you to stream movies, TV shows, photos and music from your computer to your HDTV or home theater system; 802.11a/b/g/n wireless LAN. \nLearn more about smart products.",
        "quantity": 46,
        "salePrice": 89.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/4854/4854433_sc.jpg",
        "shipping": "Free shipping",
        "id": 10
    },
    {
        "name": "Monthly Accidental Protection Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 48,
        "salePrice": 9.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 11
    },
    {
        "name": "Insignia™ - 4' Lightning Charge-and-Sync Cable",
        "shortDescription": "Compatible with select Apple® iPad®, iPhone® and iPod® models; lets you charge and sync Apple devices; 4' length",
        "quantity": 49,
        "salePrice": 14.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019369_sc.jpg",
        "shipping": null,
        "id": 12
    },
    {
        "name": "Apple® - EarPods™ with Remote and Mic - White",
        "shortDescription": "In-line remote and mic; compatible with select Apple iPhone, iPod and iPad models; sweat- and water-resistant design",
        "quantity": 52,
        "salePrice": 29.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6848/6848136_sc.jpg",
        "shipping": null,
        "id": 13
    },
    {
        "name": "HP - 564XL Ink Cartridge - Black",
        "shortDescription": "Compatible with select HP Photosmart printers; black ink; 1 cartridge",
        "quantity": 53,
        "salePrice": 23.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1982/1982034_sc.jpg",
        "shipping": "Free shipping",
        "id": 14
    },
    {
        "name": "SanDisk - Ultra Plus 32GB SDHC Class 10 UHS-1 Memory Card",
        "shortDescription": "Compatible with most devices with a SDHC card slot; 32GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
        "quantity": 58,
        "salePrice": 24.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142553_sc.jpg",
        "shipping": "Free shipping",
        "id": 15
    },
    {
        "name": "SanDisk - Cruzer 32GB USB 2.0 Flash Drive - Black",
        "shortDescription": "High-speed USB 2.0 interface for fast data transfer; U3 enabled; PC and Mac compatible",
        "quantity": 60,
        "salePrice": 14.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9288/9288807_sc.jpg",
        "shipping": "Free shipping",
        "id": 16
    },
    {
        "name": "SanDisk - Ultra Plus 32GB microSDHC Class 10 UHS-1 Memory Card",
        "shortDescription": "Compatible with most devices with a microSDHC card slot; 32GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
        "quantity": 63,
        "salePrice": 24.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142635_sc.jpg",
        "shipping": "Free shipping",
        "id": 17
    },
    {
        "name": "The Raid 2 (2 Disc) (Unrated) (Ultraviolet Digital Copy) (Blu-ray Disc)",
        "shortDescription": null,
        "quantity": 64,
        "salePrice": 19.99,
        "type": "Movie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6938/6938047.jpg",
        "shipping": null,
        "id": 18
    },
    {
        "name": "Dynex™ - 6' HDMI Cable",
        "shortDescription": "Connects an HDMI source to an HDTV or projector with an HDMI input; supports HDMI Ethernet Channel (HEC) and Audio Return Channel (ARC); compatible with most screen refresh rates",
        "quantity": 65,
        "salePrice": 19.99,
        "manufacturer": "Dynex™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/2648/2648583_sc.jpg",
        "shipping": null,
        "id": 19
    },
    {
        "name": "LG - 8x External Double-Layer DVD±RW/CD-RW Drive",
        "shortDescription": "USB 2.0 interface; slim, portable design; up to 6x DVD+R DL and DVD-R DL, 8x DVD+R and DVD-R write speeds; up to 6x DVD+RW and DVD-RW rewrite speeds; 24x24x24 CD-RW",
        "quantity": 5,
        "salePrice": 39.99,
        "manufacturer": "LG",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1802/1802006_sc.jpg",
        "shipping": "Free shipping",
        "id": 20
    },
    {
        "name": "Insignia™ - 6' HDMI Cable - Black",
        "shortDescription": "Connects 1 HDMI component to another HDMI component via HDMI connection; supports 1080p high-definition resolution; up to 10.2 Gbps bandwidth; 6' length",
        "quantity": 90,
        "salePrice": 19.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/4127/4127007_sc.jpg",
        "shipping": null,
        "id": 21
    },
    {
        "name": "Dynex™ - 3.9' HDMI Cable - Black",
        "shortDescription": "Connects 2 HDMI components; supports HEC (HDMI Ethernet Channel) and ARC (Audio Return Channel)",
        "quantity": 88,
        "salePrice": 9.99,
        "manufacturer": "Dynex™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5681/5681548_sc.jpg",
        "shipping": null,
        "id": 22
    },
    {
        "name": "SanDisk - Ultra Plus 16GB microSDHC Class 10 UHS-1 Memory Card",
        "shortDescription": "Compatible with most devices with a microSDHC card slot; 16GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
        "quantity": 38,
        "salePrice": 14.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142599_sc.jpg",
        "shipping": "Free shipping",
        "id": 23
    },
    {
        "name": "SanDisk - Cruzer 8GB USB 2.0 Flash Drive - Black",
        "shortDescription": "For PC, Mac and Linux; retractable USB connector; drag-and-drop file backup; includes SanDisk SecureAccess software; access to 2GB of YuuWaa Cloud storage",
        "quantity": 75,
        "salePrice": 5.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9226/9226777_sc.jpg",
        "shipping": "Free shipping",
        "id": 24
    },
    {
        "name": "SanDisk - Ultra 8GB SDHC UHS-I Class 10 Memory Card",
        "shortDescription": "Compatible with most digital cameras and camcorders with a SDHC slot; 8GB capacity; up to 30MB/sec. read and write speeds; durable design",
        "quantity": 78,
        "salePrice": 12.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5577/5577795_sc.jpg",
        "shipping": "Free shipping",
        "id": 25
    },
    {
        "name": "HP - 564 3-Pack Cyan/Magenta/Yellow Original Ink Cartridges - Cyan/Magenta/Yellow",
        "shortDescription": "Compatible with select HP Photosmart printers; cyan, magenta and yellow ink; 20 sheets of photo paper",
        "quantity": 6,
        "salePrice": 29.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6502/6502226_105x105_sc.jpg",
        "shipping": "Free shipping",
        "id": 26
    },
    {
        "name": "Asus - 15.6\" Laptop - Intel Celeron - 4GB Memory - 500GB Hard Drive - Black",
        "shortDescription": "Windows 8.1 64-bitTechnical details: Intel® Celeron® processor; 15.6\" display; 4GB memory; 500GB hard driveSpecial features: HDMI output",
        "quantity": 88,
        "salePrice": 249.99,
        "manufacturer": "Asus",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7288/7288011_sc.jpg",
        "shipping": "Free shipping",
        "id": 27
    },
    {
        "name": "Insignia™ - 4' Micro USB Cable - Black",
        "shortDescription": "Compatible with most micro USB-enabled devices; lets you charge and transfer data to compatible devices; sync capability; low-profile design; 4' length",
        "quantity": 39,
        "salePrice": 14.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019341_sc.jpg",
        "shipping": null,
        "id": 28
    },
    {
        "name": "Sony - PlayStation 4 (500GB)",
        "shortDescription": "Experience the evolution of gaming",
        "quantity": 95,
        "salePrice": 399.99,
        "manufacturer": "Sony",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/8240/8240103_sc.jpg",
        "shipping": "Free shipping",
        "id": 29
    },
    {
        "name": "Microsoft Office 365 Personal (1 Mac or PC + 1 Tablet) (1-Year Subscription) - Mac/Windows",
        "shortDescription": "Access amazing tools and features, no matter where you are",
        "quantity": 97,
        "salePrice": 69.99,
        "manufacturer": "Microsoft",
        "type": "Software",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5058/5058004_sc.jpg",
        "shipping": "Free shipping",
        "id": 30
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 47,
        "salePrice": 14.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 31
    },
    {
        "name": "Trend Micro Internet Security (3-Device) (1-Year Subscription) - Mac/Windows",
        "shortDescription": "Defend up to 3 devices against virtual intruders and online threats",
        "quantity": 101,
        "salePrice": 49.99,
        "manufacturer": "Trend Micro",
        "type": "Software",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5147/5147463_sc.jpg",
        "shipping": "Free shipping",
        "id": 32
    },
    {
        "name": "Apple® - $15 iTunes Gift Card",
        "shortDescription": "Redeemable at the iTunes store, iBookstore or the App Store; redeemable for music, movies, eBooks, apps and more; $15 value",
        "quantity": 106,
        "salePrice": 15,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3695/3695167_sc.jpg",
        "shipping": "Free shipping",
        "id": 33
    },
    {
        "name": "WD - My Passport Ultra 1TB External USB 3.0 Hard Drive - Black",
        "shortDescription": "USB 3.0 interface; password protection; hardware encryption; data transfer rates up to 480 Mbps",
        "quantity": 34,
        "salePrice": 69.99,
        "manufacturer": "WD",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9028/9028431_sc.jpg",
        "shipping": "Free shipping",
        "id": 34
    },
    {
        "name": "Apple® - USB Power Adapter - White",
        "shortDescription": "Compatible with all iPhone® and iPod models",
        "quantity": 67,
        "salePrice": 18.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6653/6653042_105x105_sc.jpg",
        "shipping": null,
        "id": 35
    },
    {
        "name": "SanDisk - Extreme PLUS 32GB microSDHC UHS-I Class U-1 Memory Card",
        "shortDescription": "Compatible with most devices with a microSDHC slot; includes SD/SDHC/SDXC adapter; 32GB capacity; Ultra High Speed (UHS-I) bus architecture",
        "quantity": 8,
        "salePrice": 34.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9387/9387066_sc.jpg",
        "shipping": "Free shipping",
        "id": 36
    },
    {
        "name": "ZAGG - InvisibleSHIELD Glass Screen Protector for Apple® iPhone® 5, 5s and 5c",
        "shortDescription": "Compatible with Apple iPhone 5, 5s and 5c; tempered-glass material; smooth touch; tapered edges; easy-to-install design",
        "quantity": 34,
        "salePrice": 39.99,
        "manufacturer": "ZAGG",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3699/3699012_sc.jpg",
        "shipping": "Free shipping",
        "id": 37
    },
    {
        "name": "Rocketfish™ - 4' In-Wall HDMI Cable",
        "shortDescription": "Connects an HDMI component to an HDTV or projector with an HDMI input; 3-layer cable shielding; 360° metal connector shell; silver content soldering; 24K gold-plated contacts",
        "quantity": 64,
        "salePrice": 29.99,
        "manufacturer": "Rocketfish™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3720/3720002_sc.jpg",
        "shipping": null,
        "id": 38
    },
    {
        "name": "SanDisk - Extreme PLUS 32GB SDHC UHS-I Memory Card",
        "shortDescription": "Compatible with most digital cameras and camcorders with a SDHC slot; 32GB capacity; up to 80MB/sec. read speeds and up to 60MB/sec. write speeds",
        "quantity": 87,
        "salePrice": 34.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3990/3990822_sc.jpg",
        "shipping": "Free shipping",
        "id": 39
    },
    {
        "name": "HP - 564 Black Vivera Original Ink Cartridge - Black",
        "shortDescription": "Compatible with HP d5460, ps pro68550, psc6380 and psc6760 printers; dries instantly and resists smudges; dark black",
        "quantity": 34,
        "salePrice": 12.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/8891/8891853_105x210_sc.jpg",
        "shipping": "Free shipping",
        "id": 40
    },
    {
        "name": "RCA - Indoor HDTV Antenna - White",
        "shortDescription": "Receives local HD and digital TV broadcasts; supports VHF and UHF frequencies; flat design",
        "quantity": 125,
        "salePrice": 18.99,
        "manufacturer": "RCA",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/8939/8939839_rc.jpg",
        "shipping": null,
        "id": 41
    },
    {
        "name": "Apple® - $25 iTunes Gift Card",
        "shortDescription": "Redeemable at the iTunes Store, iBookstore or the App Store; redeemable for music, movies, eBooks, apps and more; $25 value",
        "quantity": 86,
        "salePrice": 25,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3695/3695176_sc.jpg",
        "shipping": "Free shipping",
        "id": 42
    },
    {
        "name": "HP - Pavilion 17.3\" Laptop - AMD A8 - 4GB Memory - 750GB Hard Drive - Anodized Silver",
        "shortDescription": "Windows 8.1 64-bitTechnical details: AMD A8-Series processor; 17.3\" display; 4GB memory; 750GB hard driveSpecial features: HDMI output",
        "quantity": 129,
        "salePrice": 379.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5862/5862002_sc.jpg",
        "shipping": "Free shipping",
        "id": 43
    },
    {
        "name": "Apple® - MacBook Air® (Latest Model) - 13.3\" Display - Intel Core i5 - 4GB Memory - 128GB Flash Storage",
        "shortDescription": "4th Gen Intel® Core™ i5 processor; 13.3\" display; 4GB memory; 128GB flash storageSpecial features: Bluetooth 4.0Note: DVD/CD drive not included",
        "quantity": 97,
        "salePrice": 949.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/2712/2712009_sc.jpg",
        "shipping": "Free shipping",
        "id": 44
    },
    {
        "name": "Apple - USB Cable Adapter",
        "shortDescription": "USB - Proprietary Connector",
        "quantity": 32,
        "salePrice": 18.99,
        "manufacturer": "Apple",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1551/1551069_sc.jpg",
        "shipping": null,
        "id": 45
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 100,
        "salePrice": 19.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 46
    },
    {
        "name": "SanDisk - Ultra Plus 64GB microSDXC Class 10 UHS-1 Memory Card",
        "shortDescription": "Compatible with most devices with a microSDXC slot; 64GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
        "quantity": 87,
        "salePrice": 49.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142644_sc.jpg",
        "shipping": "Free shipping",
        "id": 47
    },
    {
        "name": "Fitbit - Flex Wireless Activity and Sleep Tracker Wristband - Black",
        "shortDescription": "Measures steps, distance, calories burned and active minutes; monitors sleep cycle; silent alarm; LED lights; water-resistant design; rechargeable battery",
        "quantity": 135,
        "salePrice": 99.99,
        "manufacturer": "Fitbit",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/8390/8390054_sc.jpg",
        "shipping": "Free shipping",
        "id": 48
    },
    {
        "name": "Redeemer of Souls [Deluxe Edition] - CD",
        "shortDescription": null,
        "quantity": 87,
        "salePrice": 17.99,
        "manufacturer": "Epic (USA)",
        "type": "Music",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6523/6523078.jpg",
        "shipping": null,
        "id": 49
    },
    {
        "name": "Sony - DualShock 4 Wireless Controller for PlayStation 4",
        "shortDescription": "Experience the evolution of controllers",
        "quantity": 15,
        "salePrice": 59.99,
        "manufacturer": "Sony",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/8240/8240079_sc.jpg",
        "shipping": "Free shipping",
        "id": 50
    },
    {
        "name": "Insignia™ - Micro USB Wall Charger",
        "shortDescription": "Compatible with most micro USB-enabled devices; 12W of power; 2.4-amp output; folding blades; power-indicator LED; includes 4' micro USB charge-and-sync cable",
        "quantity": 55,
        "salePrice": 19.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5689/5689149_sc.jpg",
        "shipping": null,
        "id": 51
    },
    {
        "name": "LG - Tone Pro Bluetooth Headset",
        "shortDescription": "Compatible with most Bluetooth 3.0-enabled cell phones; 3D NeckBehind design; HD Voice and aptX technologies; echo cancellation; noise reduction; Google Voice Actions integration; in-line controls",
        "quantity": 75,
        "salePrice": 69.99,
        "manufacturer": "LG",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/4950/4950032_sc.jpg",
        "shipping": "Free shipping",
        "id": 52
    },
    {
        "name": "NETGEAR - RangeMax Dual-Band Wireless-N Router with 4 Ethernet Ports",
        "shortDescription": "ENERGY STAR Certified\nUp to 600 Mbps data transfer rates; Push'N'Connect setup; broadband usage meter",
        "quantity": 27,
        "salePrice": 74.99,
        "manufacturer": "NETGEAR",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1208/1208844_105x105_sc.jpg",
        "shipping": "Free shipping",
        "id": 53
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 83,
        "salePrice": 14.99,
        "type": "BlackTie",
        "image": null,
        "shipping": "Free shipping",
        "id": 54
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 28,
        "salePrice": 8.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 55
    },
    {
        "name": "Frigidaire - Semi-Rigid Dryer Vent Kit Required for Hook-Up - Silver",
        "shortDescription": "Expandable vent; custom fitted ends and clamps",
        "quantity": 38,
        "salePrice": 26.99,
        "manufacturer": "Frigidaire",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9282/9282812_sc.jpg",
        "shipping": "Free shipping",
        "id": 56
    },
    {
        "name": "Insignia™ - 19\" Class (18-1/2\" Diag.) - LED - 720p - 60Hz - HDTV",
        "shortDescription": "ENERGY STAR Certified",
        "quantity": 87,
        "salePrice": 89.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/2799/2799043_sc.jpg",
        "shipping": "Free shipping",
        "id": 57
    },
    {
        "name": "Insignia™ - AC Laptop Power Adapter",
        "shortDescription": "Compatible with select laptops that require 90W of power or less; 19V output; thermal, over-current and short-circuit protection",
        "quantity": 23,
        "salePrice": 54.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5202/5202025_sc.jpg",
        "shipping": "Free shipping",
        "id": 58
    },
    {
        "name": "Insignia™ - 32\" Class (31-1/2\" Diag.) - LED - 720p - 60Hz - HDTV",
        "shortDescription": "ENERGY STAR Certified",
        "quantity": 45,
        "salePrice": 179.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3356/3356036_sc.jpg",
        "shipping": "Free shipping",
        "id": 59
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 56,
        "salePrice": 29.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 60
    },
    {
        "name": "Samsung - Galaxy S 5 4G LTE Cell Phone - Charcoal Black (Verizon Wireless)",
        "shortDescription": "Qualcomm Snapdragon 801 MSM 8974AC 2.5GHz quad-core processorAndroid 4.4.2 KitKat operating system4G LTE speedWi-Fi5.1\" Super AMOLED touch screen",
        "quantity": 89,
        "salePrice": 749.99,
        "manufacturer": "Samsung",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/4811/4811019_sc.jpg",
        "shipping": "Free shipping",
        "id": 61
    },
    {
        "name": "Apple® - 6.6' Lightning-to-USB 2.0 Cable",
        "shortDescription": "Compatible with most Apple® iPad®, iPhone® and iPod® models with a Lightning connector; charges and syncs your device; reversible design",
        "quantity": 23,
        "salePrice": 29.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/2253/2253772_sc.jpg",
        "shipping": null,
        "id": 62
    },
    {
        "name": "Garmin - nüvi 42LM Essential Series 4.3\" GPS with Lifetime Map Updates",
        "shortDescription": "Preloaded base map coverage of the lower 48 U.S. states, Hawaii, Puerto Rico, U.S. Virgin Islands, Cayman Islands and Bahamas; 4.3\" touch-screen display; text-to-speech technology",
        "quantity": 8,
        "salePrice": 89.99,
        "manufacturer": "Garmin",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7534/7534182_105x210_sc.jpg",
        "shipping": "Free shipping",
        "id": 63
    },
    {
        "name": "Bad Words (2 Disc) (Ultraviolet Digital Copy) (Blu-ray Disc)",
        "shortDescription": null,
        "quantity": 364,
        "salePrice": 22.99,
        "type": "Movie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/2516/25169179.jpg",
        "shipping": null,
        "id": 64
    },
    {
        "name": "HP - 61 Inkjet Cartridge Twin-Pack - Black, Yellow, Cyan, Magenta",
        "shortDescription": "Combo pack contains 1 black ink cartridge and 1 tricolor ink cartridge",
        "quantity": 96,
        "salePrice": 33.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1260/1260042_sc.jpg",
        "shipping": "Free shipping",
        "id": 65
    },
    {
        "name": "Apple® - Lightning to 30-Pin Adapter",
        "shortDescription": "Compatible with iPhone® 5, iPod touch® (5th generation), iPod nano® (7th generation); 0.2m cable length",
        "quantity": 19,
        "salePrice": 25.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6651/6651936_sc.jpg",
        "shipping": null,
        "id": 66
    },
    {
        "name": "Insignia™ - 4' Lightning Charge-and-Sync Cable",
        "shortDescription": "Compatible with select Apple® iPad®, iPhone® and iPod® models; lets you charge and sync Apple devices; 4' length",
        "quantity": 46,
        "salePrice": 14.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019104_sc.jpg",
        "shipping": null,
        "id": 67
    },
    {
        "name": "Rocketfish™ - Tilting Wall Mount for Most 32\" to 70\" Flat-Panel TVs",
        "shortDescription": "Compatible with most 32\" - 70\" flat-panel TVs; fingertip tilt; powdercoat finish; locking mechanism",
        "quantity": 27,
        "salePrice": 119.99,
        "manufacturer": "Rocketfish™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9881/9881868_rc.jpg",
        "shipping": "Free shipping",
        "id": 68
    },
    {
        "name": "Smart Choice - Dishwasher Installation Kit with Power Cord",
        "shortDescription": "6' stainless steel waterline; 5' power cord; all hardware & fittings included; no special tools needed",
        "quantity": 87,
        "salePrice": 29.99,
        "manufacturer": "Smart Choice",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6681/6681708_sc.jpg",
        "shipping": "Free shipping",
        "id": 69
    },
    {
        "name": "Apple® - 12W USB Power Adapter",
        "shortDescription": "Compatible with select Apple iPad®, iPhone® and iPod® models; compact design; Lightning connector; 12W of power",
        "quantity": 12,
        "salePrice": 19.99,
        "manufacturer": "Apple®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7006/7006915_sc.jpg",
        "shipping": null,
        "id": 70
    },
    {
        "name": "Targus - AC Adapter",
        "shortDescription": "90 W For Notebook",
        "quantity": 75,
        "salePrice": 49.99,
        "manufacturer": "Targus",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3560/3560608_sc.jpg",
        "shipping": "Free shipping",
        "id": 71
    },
    {
        "name": "Monthly Accidental Protection Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 18,
        "salePrice": 9.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 72
    },
    {
        "name": "Insignia™ - 4' Micro USB 3.0 Charge-and-Sync Cable",
        "shortDescription": "Compatible with Samsung Galaxy S 5, Note 3, Note 4 and Tab 4 models; lets you charge and sync compatible devices; 4' length",
        "quantity": 12,
        "salePrice": 19.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6380/6380169_sc.jpg",
        "shipping": null,
        "id": 73
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 17,
        "salePrice": 11.99,
        "type": "BlackTie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
        "shipping": "Free shipping",
        "id": 74
    },
    {
        "name": "ZAGG - InvisibleSHIELD Glass Screen Protector for Samsung Galaxy S 5 Cell Phones",
        "shortDescription": "Compatible with Samsung Galaxy S 5 cell phones; tempered-glass material; smooth touch; tapered edges; simple installation",
        "quantity": 98,
        "salePrice": 39.99,
        "manufacturer": "ZAGG",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5147/5147175_sc.jpg",
        "shipping": "Free shipping",
        "id": 75
    },
    {
        "name": "Rocketfish™ Mobile - 3.3' Lightning USB Charge/Sync Cable - Black",
        "shortDescription": "Compatible with Apple® iPad® 4th generation, iPad mini, iPhone® 5, iPod® touch 5th generation and iPod nano 7th generation; syncs and charges your device",
        "quantity": 12,
        "salePrice": 11.99,
        "manufacturer": "Rocketfish™ Mobile",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7334/7334069_sc.jpg",
        "shipping": null,
        "id": 76
    },
    {
        "name": "Bose® - SoundLink® Mini Bluetooth Speaker",
        "shortDescription": "Compatible with most Bluetooth-enabled devices; charging cradle; 1-piece, anodized-aluminum housing; lithium-ion battery; ultra-compact design",
        "quantity": 98,
        "salePrice": 199.99,
        "manufacturer": "Bose®",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9154/9154107_sc.jpg",
        "shipping": "Free shipping",
        "id": 77
    },
    {
        "name": "Microsoft - Surface Pro 3 - 128GB - Intel i5 - Silver",
        "shortDescription": "12\" touch screen with 2160 x 1440 resolutionWindows 8.1 Pro operating system128GB storage capacity4th generation Intel® Core™ i5 ProcessorMulti-position Kickstand",
        "quantity": 76,
        "salePrice": 999.99,
        "manufacturer": "Microsoft",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6243/6243045_sc.jpg",
        "shipping": "Free shipping",
        "id": 78
    },
    {
        "name": "Smart Choice - 6' Stainless-Steel Washing Machine Fill Hose (2-Pack) Required for Hook-Up",
        "shortDescription": "For hot and cold water; each 6' long; stainless-steel; corrosion-resistant; rubber washers included",
        "quantity": 12,
        "salePrice": 29.99,
        "manufacturer": "Smart Choice",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5446/5446387_sc.jpg",
        "shipping": "Free shipping",
        "id": 79
    },
    {
        "name": "Microsoft - Special Edition Camouflage Wireless Controller for Xbox 360 - Camouflage",
        "shortDescription": "Sneak up on your opponents and ambush them with precision and control",
        "quantity": 65,
        "salePrice": 29.99,
        "manufacturer": "Microsoft",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1935/1935591_sc.jpg",
        "shipping": null,
        "id": 80
    },
    {
        "name": "NETGEAR - Wireless-N Router",
        "shortDescription": "Wireless-N (draft 802.11n) interface; up to 300 Mbps transfer rates; advanced network security features",
        "quantity": 195,
        "salePrice": 39.99,
        "manufacturer": "NETGEAR",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/8998/8998506_rc.jpg",
        "shipping": "Free shipping",
        "id": 81
    },
    {
        "name": "Roku - Streaming Stick HDMI Version",
        "shortDescription": "Provides access to more than 1,000 channels of streaming content; lets you play personal videos, photos and music; compatible with most TVs with an HDMI input; supports up to 1080p resolution; 1-stop search",
        "quantity": 12,
        "salePrice": 49.99,
        "manufacturer": "Roku",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/4591/4591008_sc.jpg",
        "shipping": "Free shipping",
        "id": 82
    },
    {
        "name": "2-Year Replacement Plan - Geek Squad",
        "shortDescription": "",
        "quantity": 65,
        "salePrice": 19.99,
        "type": "BlackTie",
        "image": null,
        "shipping": "Free shipping",
        "id": 83
    },
    {
        "name": "Insignia™ - 4' 30-Pin Charge-and-Sync Cable",
        "shortDescription": "Compatible with most Samsung tablets with 30-pin connectors; charge and sync capabilities; 4' length",
        "quantity": 96,
        "salePrice": 14.99,
        "manufacturer": "Insignia™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019305_sc.jpg",
        "shipping": null,
        "id": 84
    },
    {
        "name": "Sony - Smart Wi-Fi Built-In Blu-ray Player",
        "shortDescription": "Plays DVD and Blu-ray; 1080p HD video output; coaxial digital audio output\nLearn more about smart products.",
        "quantity": 14,
        "salePrice": 89.99,
        "manufacturer": "Sony",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/3412/3412007_sc.jpg",
        "shipping": "Free shipping",
        "id": 85
    },
    {
        "name": "Boise - X-9 Multipurpose Paper",
        "shortDescription": "Compatible with copiers, plain paper faxes, laser printers and inkjet printers; 8.5\" x 11\" size; 500 sheets; acid-free; high opacity; 96 brightness",
        "quantity": 34,
        "salePrice": 5.99,
        "manufacturer": "Boise",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/2343/2343272_sc.jpg",
        "shipping": "Free shipping",
        "id": 86
    },
    {
        "name": "HP - ENVY 5530 Wireless e-All-In-One Printer",
        "shortDescription": "3-in-1 functionalityPrints up to 8.8 ISO ppm in black, up to 5.2 ISO ppm in color (Print speeds vary with use. See manufacturer for info on print speeds.)2.7\" color touch screen100-sheet input trayBuilt-in wireless LAN",
        "quantity": 122,
        "salePrice": 99.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1491/1491822_sc.jpg",
        "shipping": "Free shipping",
        "id": 87
    },
    {
        "name": "Motorola - SURFboard eXtreme DOCSIS 3.0 Wireless-N Cable Modem and Gigabit Router",
        "shortDescription": "4 Gigabit Ethernet ports; DOCSIS 3.0 technology; up to 300 Mbps downstream data speeds; 8x4 channel bonding; plug-and-play installation",
        "quantity": 64,
        "salePrice": 135.99,
        "manufacturer": "Motorola",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9962/9962417_rc.jpg",
        "shipping": "Free shipping",
        "id": 88
    },
    {
        "name": "Office 365 University (2 Macs or PCs) (4-Year Subscription) - Mac/Windows",
        "shortDescription": "Create, connect and learn across campus and around the world",
        "quantity": 9,
        "salePrice": 79.99,
        "manufacturer": "Microsoft",
        "type": "Software",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7016/7016181_105x105_sc.jpg",
        "shipping": "Free shipping",
        "id": 89
    },
    {
        "name": "Griffin Technology - PowerJolt SE Lightning Vehicle Charger",
        "shortDescription": "Compatible with select Apple® iPhone®, iPad® and iPod® devices; LED power indicator; SmartFuse technology; flared plugs; 10 watts of power; 2' coiled cable",
        "quantity": 12,
        "salePrice": 17.99,
        "manufacturer": "Griffin Technology",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7087/7087148_105x105_sc.jpg",
        "shipping": "Free shipping",
        "id": 90
    },
    {
        "name": "Lego Movie (2 Disc) (Ultraviolet Digital Copy) (Blu-ray Disc)",
        "shortDescription": null,
        "quantity": 86,
        "salePrice": 22.99,
        "type": "Movie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/5863/5863038.jpg",
        "shipping": null,
        "id": 91
    },
    {
        "name": "GoPro - Hero3+ Black Edition Camera",
        "shortDescription": "12.0MP digital still resolution; 4Kp15, 2.7Kp30, 1440p48, 1080p60, 960p100 and 720p120 fps video capture; Auto Low Light mode; up to 4K video resolution; SuperView mode; wearable, mountable design; waterproof housing",
        "quantity": 9,
        "salePrice": 399.99,
        "manufacturer": "GoPro",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1617/1617684_sc.jpg",
        "shipping": "Free shipping",
        "id": 92
    },
    {
        "name": "HP - 15.6\" Laptop - Intel Core i3 - 4GB Memory - 750GB Hard Drive - Black Licorice",
        "shortDescription": "Windows 8.1 64-bitTechnical details: 4th Gen Intel® Core™ i3 processor; 15.6\" display; 4GB memory; 750GB hard driveSpecial features: HDMI output",
        "quantity": 143,
        "salePrice": 379.99,
        "manufacturer": "HP",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6060/6060259_sc.jpg",
        "shipping": "Free shipping",
        "id": 93
    },
    {
        "name": "Dynex™ - 6' USB 2.0 A/B Cable",
        "shortDescription": "Connects USB 2.0 devices; supports high-speed data transfer rates up to 480 Mbps; A-male to B-male connectors",
        "quantity": 76,
        "salePrice": 24.99,
        "manufacturer": "Dynex™",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9695/9695523_sc.jpg",
        "shipping": "Free shipping",
        "id": 94
    },
    {
        "name": "SanDisk - Ultra 32GB USB 3.0 Flash Drive",
        "shortDescription": "Up to 80MB/sec. read speed; USB 3.0 interface; SanDisk SecureAccess software",
        "quantity": 32,
        "salePrice": 19.99,
        "manufacturer": "SanDisk",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9211/9211069_sc.jpg",
        "shipping": "Free shipping",
        "id": 95
    },
    {
        "name": "Amazon - Leather Case for Kindle Paperwhite - Royal Purple",
        "shortDescription": "Compatible with Kindle Paperwhite; leather material; wakes or puts your device to sleep when the case is opened or closed; form-fitting interior; magnetic clasp; thin, lightweight design",
        "quantity": 123,
        "salePrice": 39.99,
        "manufacturer": "Amazon",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/6599/6599099_105x105_sc.jpg",
        "shipping": "Free shipping",
        "id": 96
    },
    {
        "name": "NETGEAR - 8-Port Gigabit Ethernet Switch",
        "shortDescription": "ENERGY STAR Certified\nEight 10/100/1000 Mbps switched ports; high-speed auto sensing; full-duplex connections",
        "quantity": 62,
        "salePrice": 64.99,
        "manufacturer": "NETGEAR",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/7451/7451964_sc.jpg",
        "shipping": "Free shipping",
        "id": 97
    },
    {
        "name": "Cloudy With a Chance of Meatballs (DVD)",
        "shortDescription": null,
        "quantity": 8,
        "salePrice": 4.99,
        "type": "Movie",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/9685/9685975.jpg",
        "shipping": null,
        "id": 98
    },
    {
        "name": "Logitech - M570 Wireless Trackball - Gray/Blue",
        "shortDescription": "Optical technology; sculpted shape; scroll wheel; 4 buttons; wireless design",
        "quantity": 2,
        "salePrice": 35.99,
        "manufacturer": "Logitech",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1260/1260761_sc.jpg",
        "shipping": "Free shipping",
        "id": 99
    },
    {
        "name": "Google - Nexus 7 - 16GB - Black",
        "shortDescription": "7\" touch screen with 1920 x 1200 resolutionAndroid 4.3 Jelly Bean operating system16GB storage capacityQuad-core processorWi-Fi",
        "quantity": 10,
        "salePrice": 229.99,
        "manufacturer": "Google",
        "type": "HardGood",
        "image": "http://img.bbystatic.com/BestBuy_US/images/products/1484/1484847_sc.jpg",
        "shipping": "Free shipping",
        "id": 100
    }
]

export default products;